# Setup
title: Swimmer
tagline: An invitingly simple Jekyll theme
url: https://github.com/dsillman2000/swimmer
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - _css
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - node_modules
  - package.json
  - package-lock.json

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: David Sillman
  url: https://github.com/dsillman2000

# Custom vars
version: 3.0.0
